hpe-dev-incubator/hpe-dev-portal

- content/blog/2019-05-23-brittany-journey.md
- content/home/06-grommet-2.md
- content/platform/HPE-Azure-Stack.md
- content/platform/Nimble.md
- content/platform/OneView.md
- content/platform/Simplivity.md
- content/platform/grommet.md
- content/platform/iLO.md
- gatsby-node.js
- src/components/BlogCard/index.js
- src/components/Card/index.js
- src/components/Footer/index.js
- src/components/Header/index.js
- src/components/Layout/theme.js
- src/components/Link/index.js
- src/components/index.js
- src/pages/blog/index.js
- src/pages/develop/index.js
- src/pages/platforms/index.js
- src/pages/tags/index.js
- src/templates/blog-post.js
- src/templates/platform.js
- src/templates/tags.js
Added tags ability to blogs.
Refactored code to be shared more.
Changed internal links to use Gatsby Link so they don't reload the page.
Centralized Anchor styling.
> Added platforms and tags pages.

- .eslintignore
- jest.config.js
- package.json
- setupTests.js
- src/components/Content/__tests__/__snapshots__/content.js.snap
- src/components/Hero/__tests__/__snapshots__/hero.js.snap
- yarn.lock
Added validate script that runs yarn format && yarn eslint ./
I will add yarn test to this script later when I get the tests to pass in another pr.
Added missing quotes to yarn format. It wasn't formatting many files.
> format works on all files, validate script added

- content/home/05-brittany-journey.md
- content/home/06-grommet-2.md
- gatsby-node.js
- src/components/BlogCard/index.js
- src/pages/blog/index.js
- src/pages/tags/index.js
- src/templates/blog-post.js
- src/templates/platform.js
- src/templates/tags.js
Fixes issue #44
Also fixed a couple links on the home page (grommet and blog example)
> Cleaned up blog excerpts and fixed tags to be case-insensitive

- content/newsletter/2018-aug-10.md
- content/newsletter/2018-dec-19.md
- content/newsletter/2018-oct-29.md
- content/newsletter/2018-sep-29.md
- content/newsletter/2019-apr-29.md
- content/newsletter/2019-aug-13.md
- content/newsletter/2019-dec-02.md
- content/newsletter/2019-feb-19.md
- content/newsletter/2019-jul-16.md
- content/newsletter/2019-jun-12.md
- content/newsletter/2019-mar-29.md
- content/newsletter/2019-may-29.md
- content/newsletter/2019-nov-01.md
- content/newsletter/2019-oct-04.md
- content/newsletter/2019-sep-13.md
- content/newsletter/2020-jan-06.md
- gatsby-config.js
- gatsby-node.js
- src/components/Footer/index.js
- src/pages/newsletter-archive/index.js
- src/pages/newsletter-signup/index.js
- src/templates/newsletter.js
Added newsletters.
added newsletter archive link in newsletter signup page and footer
> added newsletter archive

- content/home/01-hackshack.md
- content/home/04-workshops-on-demand.md
- src/pages/Home/index.js
update with latest home page design
> update with latest designs

- src/components/Header/index.js
- src/pages/Home/index.js
This PR replaces header links with buttons and add a search field in the global header.
> make header fields button and add search

- gatsby-node.js
- src/components/Content/index.js
- src/components/Share/index.js
- src/templates/blog-post.js
> update blog subpage with latest design

- gatsby-config.js
> add google analytics tracking

- src/components/Header/index.js
Changed site Header to align a bit more with designs and improve responsiveness
> Changed site Header to align a bit more with designs and improve responsiveness

- content/community/Twitter.md
- src/components/Footer/index.js
- src/containers/EmailCapture/index.js
> update twitter link and fix footer copy

- static/admin/config.yml
This PR updates the config.YAML file for CMS to reflect all fields in the frontmatter and add hints to few fields.
> update fields in config file

- static/admin/config.yml
This PR removes the Cloudinary integration. #173
> remove cloudinary solution

- netlify.toml
This PR adds security headers to fix #300
> add browser security headers

- static/admin/config.yml
This PR adds media and public folders for each image widget in the collections.
> fix image upload path for collections

- src/components/Header/index.js
> fix focus cuff off in the header

- src/containers/EmailCapture/index.js
Update message to follow Jakub's email
> Changed you by I

- content/platform/grommet/home.md
- content/platform/hpe-ezmeral-container-platform/home.md
- content/platform/hpe-nimble-storage/home.md
- content/platform/hpe-oneview/home.md
- content/platform/ilo-restful-api/home.md
https://github.com/hpe-dev-incubator/hpe-dev-portal/issues/299
- Added W3.CSS class `w3-container` and `w3-center` to center button
- Added `w3-margin-bottom` to add space between button and horizontal bar
> Try Now button on platform page need improvement

- content/newsletter/2021-April-06.md
- static/newsletter/apr-2021/index.html
> add april 2021 newsletter

- content/newsletter/2021-May-03.md
- static/newsletter/may-2021/index.html
This PR adds the May 2021 newsletter to the Newsletter Archive section.
> add may 2021 newsletter to archive section

- src/pages/blog/index.js
This PR adds the priority check for featured blogs to display with priority between 1 and 5 only.
> feature blogs with priority between 1 and 5

- content/blog/application-modernization-with-the-application-workbench.md
- content/blog/help-build-the-hospital-of-the-future-and-be-eligible-for-prizes.md
- content/blog/hpe-dev-launches-its-munch-learn-technical-talks.md
- content/blog/hpe-developer-community-meets-a-changing-world-head-on.md
- content/blog/hpe-discover-2021-don’t-miss-these-hpe-dev-industry-expert-talks-and-hands-on-workshops.md
- content/blog/python-how-to-use-odbc-to-connect-hpe-nonstop-sql-mx.md
This PR replaces https://developer.hpe.com/blog/help-build-the-hospital-of-the-future-and-be-eligible-for-prizes/ blog from the featured list with https://developer.hpe.com/blog/application-modernization-with-the-application-workbench/
> update featured blogs

- content/blog/hpe-discover-2021-don’t-miss-these-hpe-dev-industry-expert-talks-and-hands-on-workshops.md
This PR updates the copy of the blog  HPE Discover 2021: Don’t Miss these HPE DEV Industry Expert Talks and Hands-on Workshops
TO:
> include AI ML and Data Analytics link

- content/newsletter/2021-June-01.md
- content/newsletter/2021-May-03.md
- static/newsletter/jun-2021/index.html
This PR adds the June 2021 newsletter to the archive section.
> add june 2021 newsletter

- content/newsletter/2021-July-6.md
- static/newsletter/july-2021/index.html
This PR adds the July 2021 newsletter to the archive section.
> Add July 2021 newsletter to archive

- .eslintignore
- src/components/Header/index.js
Issue: https://github.com/hpe-dev-incubator/hpe-dev-portal/issues/568
Implement dropdown of Platforms item nav:
> Implement top level drop down menus

- .eslintignore
- content/newsletter/2021-August-02.md
- static/newsletter/aug-2021/index.html
This PR adds the August 2021 newsletter to the archive section.
> Add August 2021 newsletter to archive

- content/community/newsletter.md
- content/community/openSource.md
- src/components/Header/index.js
- https://github.com/hpe-dev-incubator/hpe-dev-portal/issues/570
- https://github.com/hpe-dev-incubator/hpe-dev-portal/issues/569
- https://github.com/hpe-dev-incubator/hpe-dev-portal/issues/573
- https://github.com/hpe-dev-incubator/hpe-dev-portal/issues/574
> Rename nav titles and fold nav items under community

- content/community/contribute.md
issue: https://github.com/hpe-dev-incubator/hpe-dev-portal/issues/575
- Add content to contribute.md
> Add contribute tile to community page

- README.md
To run Adobe Analytics plugin submodule, user will need to run `git submodule init` then `git submodule update` to start developing.
> Update readme to run submodule commands for adobe analytics plugin

- src/pages/contribute/index.js
- static/admin/config.yml
- Render Google Docs icon when a Google Doc type template is rendered
- Remove ability to create new Be a Blogger page in CMS
> Be a Blogger page - Display Google Docs icon 

- content/blog/host-based-volume-encryption-with-hpe-csi-driver-for-kubernetes.md
Issue #539 
- Add line breaks between each list item
> Lists does not render with the same fonts as paragraphs 

- content/platform/grommet/home.md
- content/platform/hpe-alletra/home.md
- content/platform/hpe-ezmeral-container-platform/home.md
- content/platform/hpe-ezmeral-data-fabric/home.md
- content/platform/hpe-nimble-storage/home.md
- content/platform/hpe-oneview/home.md
- content/platform/ilo-restful-api/home.md
- content/platform/spiffe-and-spire-projects/home.md
Issue# https://github.com/hpe-dev-incubator/hpe-dev-portal/issues/544
- Update Try Now button to match the style from Grommet's primary Button component
> Platforms Try Now button style update

- content/contribute/contribute.md
- src/pages/contribute/index.js
- Decrease description font size
- Fix spacing and add bullet points in markdown file
> Update Blogger page from new design

- src/components/BlogTabContent/index.js
Issue #742 
- Checks if new blog post is published then clears `loadMoreBlogData` storage
> New blog not showing up in All

- src/pages/skillup/index.js
- static/img/skillup/skill_up.svg
> Update to new skill up page logo

- content/blog/accessing-dtap-in-pods.md
- content/blog/application-modernization-with-the-application-workbench.md
- content/blog/be-an-hpe-dev-blogger.md
- content/blog/building-dynamic-machine-learning-pipelines-with-kubedirector.md
- content/blog/hpe-dev-launches-its-munch-learn-technical-talks.md
- content/blog/hpe-developer-community-meets-a-changing-world-head-on.md
- content/blog/on-premise-adventures-how-to-build-an-apache-spark-lab-on-kubernetes.md
- content/blog/python-how-to-use-odbc-to-connect-hpe-nonstop-sql-mx.md
- content/blog/sir-hackington-rides-again.md
- Change up featured blogs in blog page for KubeCon
> KubeCon North America 2021 featured blogs

- content/opensource/Chapel.md
- content/opensource/Grommet.md
- content/opensource/KubeDirector.md
- content/opensource/SmartSim.md
- content/opensource/Spark.md
- content/opensource/spiffe_and_spire.md
- src/pages/opensource/index.js
- static/admin/config.yml
- Add active input in CMS
- Update Open Source content with `active: true`
- Query Open Source data where `active: true`
> Add active input in CMS for Open Source page

- static/admin/config.yml
- Change field name from activeCard to active
> Change CMS field to name active

- content/newsletter/2021-December-2.md
- content/newsletter/2021-November-4.md
- static/newsletter/dec-2021/index.html
- static/newsletter/nov-2021/index.html
- Adds November and December 2021 content to the Newsletter archive page
> Add Nov and Dec newsletter to newsletter archive page

- content/newsletter/2022-January-01.md
- static/newsletter/jan-2022/index.html
Adds January 2022 content to the Newsletter archive page
> Add January 2022 content to the Newsletter archive page

- src/components/BlogTabContent/index.js
- src/hooks/use-local-storage/index.js
Issue: https://github.com/hpe-dev-incubator/hpe-dev-portal/issues/943
- Checks LocalStorage hook with `typeof window !== 'undefined' && window;` so that Gatsby's SSR does not pick up during build
- Updates propType `platform` to boolean type
> Check if window type exists

- netlify.toml
- Add branch environments with env variables
- This allows the developer to test updates from workshops-on-demand-server from either testing or staging
> Add testing, deploy preview, and testing env in netlify.toml

- src/pages/hackshack/index.js
- Correctly pass down `setOpen` function to ResponsiveContextWrapper component
- Add `/hackshack` path to WOD home card
> Fix HackShack home WOD card and video tour button

- src/pages/hackshack/index.js
update hack shack home page ml card to Mithril: Introducing Robust Identities into Istio by integrating with SPIRE
> update hackshack home page ml card

- src/components/hackshack/Card/ScheduleCard.js
**Issue:** Include email in the workshop confirmation message.
You're Registered!
You have been signed up for this workshop. Head over to your email (insert <email> here) to learn what happens next.
Your registration info: Didier is signed up for HPE GreenLake for Private Cloud API: Extract the power of the Virtual Machines as a Service (VMaaS) API
**Fix:**: Registered user should see his email in the registration confirmation screen.
> add email to wkshp confirmation page and fix background

- src/pages/hackshack/treasurehunt-terms-conditions/index.js
This PR updates the treasure hunt terms and conditions
> update treasure hunt terms conditions

- src/pages/events/index.js
> fix alignment issue on events page

- content/hackshackhome/hackshackhome.md
- content/hackshackhome/munchlearn.md
- content/hackshackhome/treasurehunt.md
- content/hackshackhome/workshop.md
- src/pages/contribute/index.js
- src/pages/hackshack/challenges/template.js
- src/pages/hackshack/index.js
- src/pages/hackshack/replays/template.js
- src/pages/hackshack/stickerwall/index.js
- src/pages/hackshack/workshops/template.js
This PR fixes the web compliance severity level 10 issues.
> add alternate text to image tags

- src/pages/hackshack/index.js
- src/pages/hackshack/treasurehunt-terms-conditions/index.js
Update Treasure Hunt TC's for Kubecon NA 2022
Update hack shack home page video
> Tc kubecon na 2022

- gatsby-config.js
- src/pages/hackshack/hpetss2023-treasurehunt-terms-conditions/index.js
- yarn.lock
Opening a PR for T&Cs for treasure hunt for TSS 2023
> Terms and conditions for TSS 2023

- src/pages/hackshack/hpediscover2023-participations-terms-conditions/index.js
- src/pages/hackshack/hpediscover2023-treasurehunt-terms-conditions/index.js
Updating T&Cs for HPE DIscover 2023
> adding HPE Discover 2023 TCs

- content/blog/announcing-chapel-1-31.md
I'm opening this PR manually after manually surfing to this repo and seeing it sitting here suggesting I open a PR, because trying to do it through the netlify interface caused it to spin off into oblivion when I hit "save" as in previous attempts:
> Create Blog “announcing-chapel-1-31”

- src/components/Feedback/FeedbackBody/FeedbackBody.js
- src/components/Feedback/index.js
- src/components/Footer/index.js
Th email in the feedback widget has to be auto-populate when the website loads initially.
> Auto_fill_onload_fixed

- src/components/Feedback/FeedbackBody/FeedbackBody.js
- src/components/Feedback/index.js
- src/components/Footer/index.js
Try for email fill-in on 1st load
> auto_fill_email_issue_on_reload_fix-1

- src/components/hackshack/Video/Video.js
This PR fixes the below issue:
https://github.com/hpe-dev-incubator/hpe-dev-portal/issues/2855
> Open youtube video on new a tab

- src/components/Header/index.js
Bug: https://github.com/hpe-dev-incubator/hpe-dev-portal/issues/2908
> Bug Fix: 2908

- src/pages/hackshack/workshops/template.js
Enhancement: https://github.com/hpe-dev-incubator/hpe-dev-portal/issues/1943
> Show workshop count on each workshop tab
